### ISSUE TITLE
unable to run 'Demo show state of component.py'

### ISSUE THREAD

**Issue by sukoi26** [salabim/salabim#50]
i get the error

```code
Traceback (most recent call last):
  File "~/salabim/sample models/Demo show state of component.py", line 29, in <module>
    Machine(x=100)
  File "~/salabim/sample models/salabim.py", line 31028, in __init__
    self.setup(**kwargs)
  File "~/salabim/sample models/Demo show state of component.py", line 20, in setup
    AnimateRectangle(rectangle0=(0, 0, 75, 75), component=self, x0=x, y0=100)
  File "~/salabim/sample models/Demo show state of component.py", line 7, in __init__
    super().__init__(self, *args, **kwargs)
  File "~/salabim/sample models/salabim.py", line 27199, in __init__
    raise ValueError(repr(parent) + " is not a component")
ValueError: <__main__.AnimateRectangle object at 0x7f34c41557d0> is not a component
```
  
linux x64  python 3.11

**Comment by salabim** [comment]
Thank you for pointing out this bug.
The file has been updated and should workmas expected now.

**Comment by sukoi26** [comment]
Th+ for quick answer
